A/A/urls.py
from django.contrib import admin
from django.urls import path ,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls',namespace='home')),
    path('account/',include('account.urls',namespace='account'))
]

A/account/urls.py
from django.urls import path
from account import views


app_name="account"
urlpatterns = [
    path('register/',views.UserRegisterView.as_view(),name='user_register'),
    path('login/', views.UserLoginView.as_view(),name='user_login'),
    path('logout/',views.UserLogoutView.as_view(),name='user_logout'),
    path('profile/<int:user_id>',views.UserProfileView.as_view(),name='user_profile'),
    path('reset/',views.UserPasswordResetView.as_view(),name='reset_password'),
    path('reset/done/',views.UserPasswordResetDoneView.as_view(),name='password_reset_done'),
    path('confirm/<uidb64>/<token>/',views.UserPasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('confirm/complete/',views.UserPasswordResetCompleteView.as_view(),name='password_reset_complete'),
    path('follow/<int:user_id>/',views.UserFollowingView.as_view(),name='user_follow'),
    path('unfollow/<int:user_id>/',views.UserUnfollowView.as_view(),name='user_unfollow'),
    path('edit_user/',views.EditeUser.as_view(),name='edit_user')
]

A/home/urls.py
from django.urls import path
from home import views



app_name = 'home'
urlpatterns = [
    path('' ,views.HomeView.as_view(),name='home'),
    path('post/<int:post_id>/<slug:post_slug>/',views.PostDetailView.as_view(),name='post_detail'),
    path('post/delete/<int:post_id>/',views.PostDeleteView.as_view(),name='post_delete'),
    path('post/update/<int:post_id>/',views.PostUpdateView.as_view(),name='post_update'),
    path('post/create/',views.PostCreateView.as_view(),name='post_create'),
    path('post/comment/<int:post_id>/', views.UserCommentsView.as_view(),name='post_comment'),
    path('post/replycomment/<int:post_id>/<int:comment_id>/',views.UserReplyCommentView.as_view(),name='user_replycomment'),
    path('like/<int:post_id>/',views.UserPostLikeView.as_view(),name='post_like'),
]

A/home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.

class Post(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE , related_name='posts')
    body = models.TextField()
    slug = models.SlugField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta :
        ordering = ('-created',)

    def __str__(self) :
        return f'{self.user}---->{self.slug}'
    
    def get_absolute_url(self):
        return reverse('home:post_detail',args=(self.id , self.slug))
    
    def likesCount(self):
        return self.pvotes.count()
    
    
    def user_can_like(self , user):
        user_like = user.uvotes.filter(post=self)
        if user_like.exists():
            return True
        return False
        

class Comment(models.Model):
    user = models.ForeignKey(User , on_delete=models.CASCADE , related_name ='ucomments')
    post = models.ForeignKey(Post , on_delete=models.CASCADE , related_name='pcomments')
    reply = models.ForeignKey('self', on_delete= models.CASCADE , related_name='rcomment' , blank=True , null=True)
    is_reply = models.BooleanField(default=False)
    body = models.TextField(max_length=400)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created',)
    def __str__(self):
        return f'{self.user} - {self.body[:30]} - {self.post}'

class Vote(models.Model):
    user = models.ForeignKey(User ,on_delete=models.CASCADE , related_name='uvotes')
    post = models.ForeignKey(Post , on_delete=models.CASCADE , related_name='pvotes')
    
    def __str__(self):
        return f'{self.user} liked {self.post.slug}'
    
     

A/home/forms.py
from django import forms
from home.models import Post, Comment



class PostCreateUpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields=('body',)
        
class CommentCreateForm(forms.ModelForm):
    class Meta :
        model = Comment
        fields = ('body',)
        widgets={
            'body':forms.Textarea(attrs={'class':'form-control'})
        }
class PostSearchForm(forms.Form):
    search = forms.CharField()
    

A/home/views.py
from django.shortcuts import render,redirect , get_object_or_404
from django.views import View
from home.models import Post ,Comment,Vote
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from home.forms import PostCreateUpdateForm , CommentCreateForm ,PostSearchForm
from django.utils.text import slugify
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
# Create your views here.


class HomeView(View):
    form_class = PostSearchForm
    def get(self , request):
        posts = Post.objects.all()
        if request.GET.get('search'):
            posts = posts.filter(body__contains=request.GET['search'])
        
        return render(request , 'home/index2.html',{'posts':posts,'form':self.form_class})
    

class PostDetailView(View):
    form_class = CommentCreateForm
    
    def setup(self , request , *args, **kwargs):
        self.post_instance = get_object_or_404(Post , pk = kwargs['post_id'] , slug = kwargs['post_slug'])
        return super().setup(request , *args, **kwargs)
        
    def get(self , request , post_id , post_slug):
        comments = self.post_instance.pcomments.filter(is_reply=False)
        can_like = False
        if request.user.is_authenticated and self.post_instance.user_can_like(request.user):
            can_like= True
        return render(request , 'home/detail.html',{'post':self.post_instance , 'comments':comments , 'form':self.form_class,'can_like':can_like})


class PostDeleteView(LoginRequiredMixin , View):
    def get(self , request , post_id):
        post = Post.objects.get(pk=post_id)
        if post.user.id == request.user.id:
            post.delete()
            messages.success(request , 'post deleted','success')
        else :
            messages.error(request ,'you cant delete this post','danger')
        return redirect('home:home')
    

class PostUpdateView(LoginRequiredMixin , View):
    form_class = PostCreateUpdateForm

    def setup(self,request ,*args, **kwargs):
        self.post_instanse = Post.objects.get(pk= kwargs['post_id'])
        return super().setup(request ,*args, **kwargs)
    
    def dispatch(self , request ,*args, **kwargs):
        post = self.post_instanse
        if not post.user.id == request.user.id :
            messages.error(request , 'you cant update this post','danger')
            return redirect('home:home')
        return super().dispatch(request , *args, **kwargs)
    def get(self ,request, *args, **kwargs):
        post = self.post_instanse
        form = self.form_class(instance=post)
        return render(request , 'home/update.html', {'form':form})

    def post(self , request , *args, **kwargs):
        post = self.post_instanse
        form = self.form_class(request.POST,instance=post)
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.slug = slugify(form.cleaned_data['body'][:30])
            new_form.save()
            messages.success(request, 'post updated', 'success')
            return redirect('home:post_detail',post.id , post.slug)
        
class PostCreateView(LoginRequiredMixin , View):
    form_class = PostCreateUpdateForm
    def get(self , request ):
        form = self.form_class
        return render(request ,'home/create.html',{'form':form})
        
    def post(self , request):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.user = request.user
            new_form.slug = slugify(form.cleaned_data['body'][:30])
            new_form.save()
            messages.success(request , 'you created new post ','success')
            return redirect('home:post_detail' , new_form.id , new_form.slug)
        
        
# poae hvie cjrh amvc
class UserCommentsView(LoginRequiredMixin,View):
    form_class = CommentCreateForm
    def get(self , request , *args, **kwargs):
        form = self.form_class
        return render(request , 'home/comment.html' ,{'form':form})
    def post(self , request , *args, **kwargs):
        form = self.form_class(request.POST)
        post = Post.objects.get(pk= kwargs['post_id'])
        if form.is_valid():
            new_comment=form.save(commit=False)
            new_comment.user = request.user
            new_comment.post = post
            new_comment.save()
            messages.success(request , 'comment posted','success')
            return redirect('home:post_detail' ,post.id , post.slug)
        messages.error('you cant comment this post')
        return redirect('home:home')
        
class UserReplyCommentView(LoginRequiredMixin, View):
    form_class = CommentCreateForm
    def get(self,request , *args, **kwargs):    
        form = self.form_class
        return render(request , 'home/replycomment.html',{'form':form})
    def post(self ,request , *args, **kwargs):
        form = self.form_class(request.POST)
        post = get_object_or_404(Post , pk =kwargs['post_id'])
        comment = get_object_or_404(Comment , pk=kwargs['comment_id'])
        if form.is_valid():
            reply = form.save(commit=False)
            reply.user = request.user
            reply.post = post
            reply.reply = comment
            reply.is_reply=True
            reply.save()
            messages.success(request,'successfull','success')
            return redirect('home:post_detail' ,post.id , post.slug)
        messages.error('you cant comment this post')
        return redirect('home:home')       

class UserPostLikeView(LoginRequiredMixin ,View):
    def get(self , request ,*args, **kwargs):
        post = get_object_or_404(Post ,pk=kwargs['post_id'])
        like = Vote.objects.filter(user=request.user , post=post)
        if like.exists() :
            messages.success(request , 'you dislike this post','danger')
            like.delete()        
        else:
            Vote.objects.create(user=request.user , post=post)
            messages.success(request , 'you liked this post','success')
        return redirect('home:post_detail',post.id,post.slug)

A/home/templates/home/comment.html
{% extends "base.html" %}
{% block content %}
<form method="post">
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value='send'>


</form>


{% endblock content %}

A/home/templates/home/create.html
{% extends "base.html" %}
{% block content %}
<form method="post" novalidate>
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Create">


</form>


{% endblock content %}

A/home/templates/home/detail.html
{% extends "base.html" %}
{% block content %}


{% if request.user.id == post.user.id %}
<a href='{% url "home:post_delete" post.id  %}' class="btn btn-danger">Delete</a>
<a href='{% url "home:post_update" post.id  %}' class="btn btn-info">Update</a>
{% endif %}


<h2 class="text-center"><a href="{% url 'account:user_profile' post.user.id %}">{{ post.user }}</a></h2>
<h4 class="text-end">{{ post.updated|date:"Y-M" }}</h4>
<p>{{ post.body }}</p><br/>


{% if request.user.is_authenticated %}
    <div class="w-100 d-flex justify-content-between">
        <a class="btn btn-primary  " href="{% url 'home:post_comment' post.id %}">comment</a>
    <a class="btn btn-{% if not can_like %}outline-{% endif %}danger col-md-3" href="{% url 'home:post_like' post.id %}">
    {{ post.likesCount }} like
    {% if not can_like %}
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16">
            <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143q.09.083.176.171a3 3 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15"/>
        </svg>
    {% else %}
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart-fill" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314"/>
        </svg>
    {% endif %}
    </a>
    </div><hr/>
        
{% else %}
    <p class="alert alert-danger"> only loged in user can comment</p>
{% endif %}


{% for comment in comments %}
    <div class="card bg-dark text-white">
        <p class="card-header">{{ comment.user }}|{{ comment.created|timesince }}</p>
        <p class="card-body">{{ comment.body }}</p>
        <a class="btn btn-primary m-3" href="{% url 'home:user_replycomment' post.id comment.id %}">reply</a>
        {% for reply in comment.rcomment.all %}
            <p class="bg-black m-3 p-2 ">{{ reply.user }} <br/>{{ reply.body }}</p>
        {% endfor %}
    </div>
<br/><hr/>
{% endfor %}
<br/>



{% endblock content %}  

A/home/templates/home/index.html
{% extends "base.html" %}

{% block content %}
<h3>Home Page</h3>

    <div class="card">
        {% for post in posts %}
            <p>Owner : {{ post.user.username }}</p>
            <a style="display:inline" href="{{ post.get_absolute_url }}" class="card-body">{{ post.body|truncatewords:8 }}</a>
            <p class="text-end">Time</p><br/><hr/>
            
        {% endfor %}

    </div>
{% endblock content %}

A/home/templates/home/index2.html
{% extends "base.html" %}

{% block content %}

<form method="get">
  {{ form.as_p }}
  <input type="submit" value="search">

</form><br/>



<div class="row">
{% for post in posts %}
    <div class="col-sm-6 mb-3 mb-sm-0">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">{{ post.user.username }}<p class="text-end">{{ post.created|timesince }}</p></h5>
          <p class="card-text">{{ post.body|truncatewords:8 }}</p>
          <a href="{{ post.get_absolute_url }}" class="btn btn-primary">more ...</a>
        </div>
      </div>
    </div>
{% endfor %}
</div>
{% endblock content %}

A/home/templates/home/replycomment.html
{% extends "base.html" %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value='send'>    
</form>


{% endblock content %}

A/home/templates/home/update.html
{% extends "base.html" %}
{% block content %}
<form method="post" novalidate>
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="UPDATE">


</form>


{% endblock content %}